### ISSUE TITLE
404

### ISSUE THREAD

**Issue by wldst** [b3log/xiaov#9]
Exception in thread "Thread-15" java.lang.RuntimeException: 请求失败，Http返回码[404]
	at com.scienjus.smartqq.client.SmartQQClient.getJsonArrayResult(SmartQQClient.java:508)
	at com.scienjus.smartqq.client.SmartQQClient.pollMessage(SmartQQClient.java:185)
	at com.scienjus.smartqq.client.SmartQQClient.access$100(SmartQQClient.java:25)
	at com.scienjus.smartqq.client.SmartQQClient$1.run(SmartQQClient.java:68)
	at java.lang.Thread.run(Thread.java:745)

**Comment by 88250** [comment]
拉一下打过补丁的[客户端实现](https://github.com/b3log/smartqq)进行本地构建，然后更新 XiaoV 最新代码重新编译构建。
